name: Run Bencher

on:
  push:

jobs:
  run-bencher:
    runs-on: windows-2019

    steps:
    - uses: bencherdev/bencher@main
    
    -name: Upload location candidate
     uses: actions/upload-artifact@v4
     with:
        name: dir
        path: C:\hostedtoolcache\windows\bencher\0.5.1\x64\*
    
    - name: Run Bencher
      shell: cmd
      run: |
        C:\hostedtoolcache\windows\bencher\0.5.1\x64\bencher.exe run "bencher mock"