name: Run Bencher

on:
  push:

jobs:
  run-bencher:
    runs-on: windows-2022

    steps:
    - name: Install Bencher CLI
      uses: bencherdev/bencher@main
    
    - name: Run Bencher
      shell: pwsh
      run: |
        curl -sSL https://install.bencher.dev | bash
        bencher --version
        bencher run "bencher mock"
