name: Run Bencher

on:
  push:

jobs:
  run-bencher:
    runs-on: windows-2019

    steps:
    - uses: bencherdev/bencher@main
    
    - name: Run Bencher
      shell: pwsh
      run: |
        bencher run --project mock "bencher mock"
        
#C:\hostedtoolcache\windows\bencher\0.5.1\x64\