name: Run Bencher

on:
  push:

jobs:
  run-bencher:
    runs-on: windows-2022

    steps:
    - name: Install Bencher CLI
      shell: pwsh
      run: |
        powershell -c "irm https://bencher.dev/download/install-cli.ps1 | iex"

    - name: Run 7zip benchmark
      shell: pwsh
      run: |
        7z b
    
    - name: Run Bencher
      shell: pwsh
      run: |
        bencher run 7z b
