name: Run Bencher

on:
  push:

jobs:
  run-bencher:
    runs-on: windows-2022

    steps:
    - name: Install Bencher CLI
      shell: pwsh
      run: |
        powershell -c "irm https://bencher.dev/download/install-cli.ps1 | iex"
        
    - name: Install 7zip
      shell: pwsh
      #run: |
        #Invoke-WebRequest -Uri "https://7-zip.org/a/7zr.exe" -OutFile "$env:TEMP\7zr.exe"
        #Start-Process "$env:TEMP\7zr.exe" -Wait

    - name: Run 7zip benchmark
      shell: pwsh
      run: |
        7z b
    
    - name: Run Bencher
      shell: pwsh
      run: |
        bencher --version
        bencher run "bencher mock"
