name: Run Bencher

on:
  push:

jobs:
  run-bencher:
    runs-on: windows-2022

    steps:
    - name: Install Bencher CLI
      shell: pwsh
      run: |
        powershell -c "irm https://bencher.dev/download/install-cli.ps1 | iex"
    
    - name: Run Bencher
      shell: pwsh
      run: |
        bencher --version
        bencher run "bencher mock"
