name: Run Bencher

on:
  push:

jobs:
  run-bencher:
    runs-on: ubuntu-latest

    steps:
    - uses: bencherdev/bencher@main
    
    - name: Run Bencher
      run: |
        bencher run "bencher mock"
        
#C:\hostedtoolcache\windows\bencher\0.5.1\x64\